[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
async-process = "2.2.3"
rocket = { version = "0.5.1", features = ["json"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
